name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest

    steps:
      - name: Set Node version
        uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Run Install
        run: yarn install --frozen-lockfile

      - name: Run Lint
        run: yarn lint

      - name: Deploy to Vercel (main branch only)
        if: github.ref == 'refs/heads/main'
        run: vercel --prod --confirm --token ${{ secrets.VERCEL_DEPLOY_TOKEN }}
