name: Node CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Check build integrity
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - run: yarn ci
      - run: yarn eslint
      - run: yarn prettier
      - run: yarn check-types
      - run: yarn build

      - name: Deploy to Vercel (only when on main branch)
        if: github.ref == 'refs/heads/main'
        run: vercel --prod --confirm --token ${{ secrets.VERCEL_DEPLOY_TOKEN }}
