on:
  push:
    branches:
      - 'main'
    paths-ignore: # Don't forget: when making changes down here, sync them with the .vercelignore file, if present.
      - '.husky/**'
      - '.vscode/**'
      - 'files'
      - 'LICENSE'
      - 'README.md'

jobs:
  workflow:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-node@v4 # https://github.com/actions/setup-node
        with:
          node-version: 20

      - uses: pnpm/action-setup@v3 # https://github.com/pnpm/action-setup
        with:
          version: 8

      - uses: actions/checkout@v4 # https://github.com/actions/checkout

      - run: pnpm i --frozen-lockfile

      - run: pnpm lint

      - run: vercel --prod --yes --token ${{ secrets.VERCEL_DEPLOY_TOKEN }}
